name: Customer-CI

on: 
  push:
    branches: abc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm-build
      run : |
       npm install 
       npm run build 
       docker build . --file Dockerfile --tag kangmin46/frontend-customer:latest 
       ls -al    
    - name: docker image push
      run: |
        docker login -u ${{secrets.DOCKER_USER_NAME}} --password ${{secrets.DOCKER_USER_PASSWORD}}
        docker push kangmin46/frontend-customer:latest
